name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release me!
      # You may pin to the exact commit or the version.
      # uses: ridedott/release-me-action@0d9eb06575c7c34690c2629b35f57109474d79e7
      uses: ridedott/release-me-action@v2.2.64

