name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      name: Release
      uses: ridedott/release-me-action@master
      with:
        release-branches: '["main"]'  
        node-module: true
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - env:
        NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      name: Publish to GitHub Packages
      run: npm publish
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npm.org'
        # Scoped packages require the scope parameter to be set in the setup
        # node step when publishing to the npm registry.
        scope: '@my-organization'
    - env:
        NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      name: Publish to npm
      run: npm publish

