name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrdivyansh/eslint-action@1.0.6
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          eslint-rc: .eslintrc.js
          execute-on-files: ./src
