name: Pre Release Script
on:
  push:
    branches:
      - beta
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["+([0-9])?(.{+([0-9]),x}).x","master","next","next-major",{"name":"beta","prerelease":"beta"},{"name":"alpha","prerelease":"alpha"}]'
          node-module: true
          commit-assets: |
            ./dist
