name: Pre Release Script
on:
  push:
    branches:
      - beta
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - run: rm .prettierrc

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["feat/github-hooks", {"name":"feat/github-hooks","prerelease": "true"}]'
          node-module: true
          commit-assets: |
            ./dist

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com/Qordobacode"
          
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --tag=beta
