name: Pre Release Script
on:
  push:
    branches:
      - beta

jobs:	
  build:	
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Beta release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["master", {"name":"beta","prerelease":"beta"}]'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npm publish --tag=beta
