name: Releases

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --frozen-lockfile

    - uses: Klemensas/action-autotag@stable
      id: update_tag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
    - name: Create Release
      if: steps.update_tag.outputs.tagname
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.update_tag.outputs.tagname }}
        release_name: Release ${{ steps.update_tag.outputs.tagname }}
        draft: false # Default value, but nice to set explicitly
        prerelease: false # Default value, but nice to set explicitly